package:
  name: nri-f5
  version: 2.7.2
  epoch: 0
  description: New Relic Infrastructure F5 Integration
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-f5
      expected-commit: 5636886916efadc67d96febb36b57d90ffff830f
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-f5
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-f5
    strip-prefix: v
