package:
  name: nri-mongodb
  version: 2.8.1
  epoch: 0
  description: New Relic Infrastructure MongoDB Integration
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-mongodb
      expected-commit: 61cce55b7d7ecf223325602d5deaa3b83e37c776
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-mongodb
      ldflags: -w

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/newrelic-infra/integrations.d
      install -Dm644 mongodb-config.yml.sample "${{targets.destdir}}"/etc/newrelic-infra/integrations.d/mongodb-config.yml.sample

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-mongodb
    strip-prefix: v
