package:
  name: nri-memcached
  version: 2.5.1
  epoch: 0
  description: New Relic Infrastructure memcached Integration
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-memcached
      expected-commit: df1824d0a43a011fce9ae51e46be27449dbd14ed
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-memcached
      ldflags: -w

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/newrelic-infra/integrations.d
      install -Dm644 memcached-config.yml.sample "${{targets.destdir}}"/etc/newrelic-infra/integrations.d/memcached-config.yml.sample

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-memcached
    strip-prefix: v
