package:
  name: nri-cassandra
  version: 2.13.2
  epoch: 0
  description: New Relic Infrastructure Cassandra Integration
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-8-jre
      - nrjmx

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-cassandra
      expected-commit: b629c78b1fc76e8c6176aeb24f43e05d6dc6de8c
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-cassandra
      ldflags: -w

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/newrelic-infra/integrations.d
      install -Dm644 cassandra-config.yml.sample "${{targets.destdir}}"/etc/newrelic-infra/integrations.d/cassandra-config.yml.sample

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-cassandra
    strip-prefix: v
