package:
  name: nri-mysql
  version: 1.10.2
  epoch: 0
  description: New Relic Infrastructure MySQL Integration
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-mysql
      expected-commit: 54fc0ed4811aaa36f7552ee0c7d551da8fd9523e
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-mysql
      ldflags: -w

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/newrelic-infra/integrations.d
      install -Dm644 mysql-config.yml.sample "${{targets.destdir}}"/etc/newrelic-infra/integrations.d/mysql-config.yml.sample

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-mysql
    strip-prefix: v
