package:
  name: nri-redis
  version: 1.11.2
  epoch: 0
  description: New Relic Infrastructure Redis Integration
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-redis
      expected-commit: 088d1ba271e1d54494f4f9cdc51c0099cf54a48d
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-redis
      ldflags: -w

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/newrelic-infra/integrations.d
      install -Dm644 redis-config.yml.sample "${{targets.destdir}}"/etc/newrelic-infra/integrations.d/redis-config.yml.sample

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-redis
    strip-prefix: v
