package:
  name: nri-kafka
  version: 3.4.9
  epoch: 0
  description: New Relic Infrastructure Kafka Integration
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - openjdk-8-jre
      - nrjmx

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-kafka
      expected-commit: 943d8fe97699afd751b7b6cdde3be6b1281ec76f
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-kafka
      ldflags: -w
      # GHSA-qppj-fm5r-hxr3, GHSA-4374-p667-p6c8 and GHSA-2wrh-6pvc-2jm9
      deps: golang.org/x/net@v0.17.0

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/newrelic-infra/integrations.d
      install -Dm644 kafka-config.yml.sample "${{targets.destdir}}"/etc/newrelic-infra/integrations.d/kafka-config.yml.sample

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-kafka
    strip-prefix: v
