package:
  name: nri-jmx
  version: 3.5.0
  epoch: 0
  description: New Relic Infrastructure JMX Integration
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-8-jre
      - nrjmx

environment:
  contents:
    packages:
      - openjdk-8

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-jmx
      expected-commit: 50396ab8085d2879c47583513bc7d89070b21b78
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-jmx
      ldflags: -w

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/newrelic-infra/integrations.d
      install -Dm644 jmx-config.yml.sample "${{targets.destdir}}"/etc/newrelic-infra/integrations.d/jmx-config.yml.sample

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-jmx
    strip-prefix: v
